### PR TITLE
Add new tracking events

### PR DESCRIPTION
**Pull request by wazolab**
- On Isochrone profile types (bike, car, pedestrian) :
```js
{
  type: 'isochrone_event'
  event: 'select_profile'
  profile: 'car' | 'bicycle' | 'foot'
}
```
- On Isochrone trigger button
```js
{
  type: 'popup_event'
  event: 'isochrone'
  poiId: ApiPoiId
  category: string
  title?: string
}
```

- Add to `map_control_event` the selected background value in case of `event=background`
```js
{
  type: 'map_control_event'
  event: 'background'
  background: 'vector' | 'aerial' | 'bicycle'
}
```

### CODE REVIEW

**Comment by frodrigo** [comment]
- Need also to update the doc.
- Map 'driving-car' | 'cycling-regular' | 'foot-walking' to simpler name 'car' | 'bicycke' | 'foot'

**Comment by frodrigo** [comment]
Te GTM and Matomo impl are missing.

**Comment by wazolab** [comment]
> Te GTM and Matomo impl are missing.

What do you mean ?
We are calling `$tracking` which is an abstraction around GTM and Matomo, si it will shoot an event on both.

**Comment by wazolab** [comment]
> * Need also to update the doc.
> * Map 'driving-car' | 'cycling-regular' | 'foot-walking' to simpler name 'car' | 'bicycke' | 'foot'

We can, I just mapped the OpenRouteService types. We could have a matching array for more human-readable labels such as :
```js
const labels = {
  'driving-car': 'car',
  'cycling-regular':  'bicycle',
  'foot-walking': 'foot'
}
```

**Comment by frodrigo** [comment]
> > * Need also to update the doc.
> > * Map 'driving-car' | 'cycling-regular' | 'foot-walking' to simpler name 'car' | 'bicycke' | 'foot'
> 
> We can, I just mapped the OpenRouteService types. We could have a matching array for more human-readable labels such as :
> 
> ```js
> const labels = {
>   'driving-car': 'car',
>   'cycling-regular':  'bicycle',
>   'foot-walking': 'foot'
> }
> ```

Yes

**Comment by frodrigo** [comment]
> Need also to update the doc.

Do not forget about the doc.

**Comment by wazolab** [comment]
Docs updated !

**Pull request merged**
