### PR TITLE
feat: init css on print #18

### PR DESCRIPTION
**Pull request by joselegitan**
First draft do not hesitate to tell me the modification needed

### CODE REVIEW

**Comment by frodrigo** [comment]
Note: storybook test, are borken right now.

**Comment by frodrigo** [comment]
Rebase.

Still need improvement https://github.com/teritorio/vido/issues/18#issuecomment-1428741518

**Comment by frodrigo** [comment]
Please, can you rebase, or port the PR to the current `develop` branch, please.

**Comment by frodrigo** [comment]
Looks good on "large" layout. But there is also small map layout with or without photo.

Like http://127.0.0.1:3000/poi/33500/details or http://127.0.0.1:3000/poi/33726/details

On the first the map is still broken.

**Comment by frodrigo** [comment]
Please, can you rebase this PR.

**Comment by joselegitan** [comment]
done

**Comment by frodrigo** [comment]
> done

I replaced the merge by a rebase on the branch

**Comment by frodrigo** [comment]
Ok, let merge it. Thank you.

**Pull request merged**
