### PR TITLE
In embedded pages on details link in new tab

### PR DESCRIPTION
**Pull request by wazolab**

### CODE REVIEW

**Comment by frodrigo** [comment]
Why not just pas a prop to `PoisTable` from the page?

**Comment by wazolab** [comment]
> Why not just pas a prop to `PoisTable` from the page?

We could actually, something like `detailsTarget: string` ?

**Comment by frodrigo** [comment]
> > Why not just pas a prop to `PoisTable` from the page?
> 
> We could actually, something like `detailsTarget: string` ?

Just a boolean, no ?

**Comment by wazolab** [comment]
> Just a boolean, no ?

I think we are setting a value for a target attribute instead of just activating the "target" isn't it ?
Or we could say `detailsIsExternal: boolean` ?

**Comment by frodrigo** [comment]
>  Or we could say `detailsIsExternal: boolean` ?

Yes that the point.

**Pull request merged**
